---
title: "Data wrangling"
author: "Marcus J Thomson"
date: "2/20/2020"
output: 
  html_document: 
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales) # install.packages("scales")
library(patchwork) # install.packages("patchwork")
```

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)
```

```{r}
annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))

head(annual_esc)
```

```{r}
ggplot(annual_esc, aes(x = Species, y = escapement, fill = SASAP.Region)) +
  geom_col()
```

```{r}

my_theme <- theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5), 
        legend.position = "bottom")

ggplot(data = annual_esc, 
       aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point() + 
  scale_y_continuous(labels = comma) + 
  labs(x = "year", 
       y = "escapement") + 
  my_theme + 
  facet_wrap(~SASAP.Region, 
             scales = "free_y", 
             ncol = 2)
```

```{r}
p1 <- ggplot(annual_esc, aes(x = Species, y = escapement)) + 
  geom_col()

p2 <- ggplot(data = annual_esc, 
       aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point() + 
  scale_y_continuous(labels = comma) + 
  labs(x = "year", 
       y = "escapement")

p1 + p2
```

